sudo: true
language: python
python:
  - "3.6"
env:
  DOCKER_COMPOSE_VERSION: 1.8.0
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
  - docker-compose --version
before_script:
  - docker-compose -f local.yml pull
  - docker-compose -f local.yml up --build -d
script:
  - docker-compose -f local.yml run --rm django python manage.py migrate
  - docker-compose -f local.yml run --rm django py.test
