sudo: true
language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - sudo apt-get update -qq
before_script:
  - docker-compose -f local.yml pull
  - docker-compose -f local.yml build
  - travis_retry docker-compose -f local.yml run django
script:
  - docker-composer -f local.yml run --rm django python manage.py migrate
  - docker-composer -f local.yml run --rm django py.test
